tokenize:
  model_name_or_path: "sshleifer/tiny-gpt2"
  max_length: 128
  local_files_only: false

extract_activations:
  tokenized_pkl_path: "data/02_intermediate/prompts_tokenized.pkl"
  model_name_or_path: "sshleifer/tiny-gpt2"
  output_root: "data/03_primary/activations"
  layers: [0, 1]
  shard_size: 2
  batch_size: 1
  local_files_only: false
  use_gpu_for_forward: false
  torch_dtype: "float32"
  device_mode: "cpu"
  allow_cpu_fallback: true

metrics_generate:
  mode: "stub"
